# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailersend" do
  name "mailersend"
  desc "Command-line interface for the MailerSend API"
  homepage "https://github.com/mailersend/mailersend-cli"
  version "1.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailersend"

  on_macos do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "ef8e8731c6b52b116b0344b07af23d5b90d1539fe2404c4116202419493b8596"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "19fa31cde92ec4bd480082f8ea78bd14a8ed1cbc143cf5ced37e0fffbc7ca8f0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_amd64.tar.gz"
      sha256 "53ebaeb3a79f1aa0094d7862021c6307bd180d89c9dcda0cf8e318c4b35e2dce"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_arm64.tar.gz"
      sha256 "efd562c8cd19b4c0ed5bf693554db83ef1737520ba5848aa69250e06f0d0a9bf"
    end
  end

  # No zap stanza required
end
