# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailersend" do
  name "mailersend"
  desc "Command-line interface for the MailerSend API"
  homepage "https://github.com/mailersend/mailersend-cli"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailersend"

  on_macos do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "cb80231eee375c9a33c607fe9f872bc71e984ea5f70c320d8961580aefb5feb0"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "841767264b6b65aa16ff23fef695c8146da3c65d1638e25e902730b8d1c2a431"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_amd64.tar.gz"
      sha256 "6888aab70aeed28b18d1fbb7b32226b1a8dea7f5e06afb230ebef9f5a051b701"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_arm64.tar.gz"
      sha256 "cacd33aa255fcfaa19da587ff2aba3cbe8efa39c3aa2c19d16481dea67f4d438"
    end
  end

  # No zap stanza required
end
