# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailersend" do
  name "mailersend"
  desc "Command-line interface for the MailerSend API"
  homepage "https://github.com/mailersend/mailersend-cli"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailersend"

  on_macos do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "1b9856184aae4f3e982a2935e9e808fc583b26bf70c63cefaced77cfccd55fb7"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "2ec0ba0f0aa0a600162ef78b9b352cb453f48070d7af99a47cdaa4d29f67e3fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_amd64.tar.gz"
      sha256 "94cfba1041aba8e8173b07d96899729e7dd35fef50f1ea0418ca569622db2d1d"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_arm64.tar.gz"
      sha256 "0438823d52bcbc7e429573eea4b2edbf0a4c8403b2d7f541ff8f95a6788508a8"
    end
  end

  # No zap stanza required
end
